//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Returned { get; set; }
        public int BookID { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public Nullable<int> CustomerAge { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<int> BookStatusID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookStatu BookStatu { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
